# Generated by Django 5.1 on 2024-10-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True)),
                ('lng', models.DecimalField(decimal_places=14, max_digits=18, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=18, verbose_name='Широта')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
