# Generated by Django 5.1 on 2024-10-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=18, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='geopoint',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=18, null=True, verbose_name='Долгота'),
        ),
    ]
