# Generated by Django 5.1 on 2024-09-06 07:04

from django.db import migrations


class Migration(migrations.Migration):
    def fill_order_price(apps, schema_editor):
        OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
        for order_product in OrderProduct.objects.all():
            order_product.price = order_product.product.price
            order_product.save()

    dependencies = [
        ('foodcartapp', '0043_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(fill_order_price)
    ]
    