# Generated by Django 5.1 on 2024-09-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_delivered_at_order_called_at_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Delivered_at',
            new_name='delivered_at',
        ),
    ]
