# Generated by Django 5.1 on 2024-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_rename_payment_tupe_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('M', 'Менеджер'), ('P', 'Сборщик'), ('C', 'Курьер'), ('A', 'Архив')], db_index=True, default='M', max_length=2, null=True, verbose_name='Статус'),
        ),
    ]
