# Generated by Django 5.1 on 2024-09-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_order_restraunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restraunt',
            new_name='restaurant',
        ),
    ]
