# Generated by Django 5.1 on 2024-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_order_restaurants_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(related_name='ready_in_restaurants', to='foodcartapp.restaurant', verbose_name='Рестораны'),
        ),
    ]
